### ISSUE TITLE
Expo & Bare RN haptic interop 

### ISSUE THREAD

**Issue by jxom** [coinjar/react-native-wagmi-charts#3]
Based on the discussion in #1.

It would be nice to have the ability to support haptic feedback in Expo managed projects (as well as bare React Native projects – which is what we support currently).

I think the ideal approach is [@andreialecu's module detection technique](https://github.com/coinjar/react-native-wagmi-charts/issues/1#issuecomment-937086879). We should list `expo-haptics` (for Expo managed projects) and `react-native-haptic-feedback` (for bare RN projects) as optional peer dependencies, and if the library detects that `expo-haptics` is installed, then prefer that over `react-native-haptic-feedback`.

**Comment by andreialecu** [comment]
I just made an attempt to implement this but it seems that optional requires are broken in the latest Metro for some weird reason. 

I've been running into: 
```
Error: Requiring unknown module "undefined". If you are sure the module exists, try restarting Metro. You may also want to run `yarn` or `npm install`.
```
This seems to be tracked at: https://github.com/facebook/metro/issues/666

Disabling `inlineRequires` didn't work, and doesn't seem like a good idea anyway.

So I think an alternative would be to simply remove the haptics implementation from the library and just provide a callback which the user can handle themselves to trigger haptics.

Meaning, instead of `enableHapticFeedback`, there would be a callback `onHapticFeedback`. 

Or it could be more generic, so that the user could do:
`onCurrentXChange={(value) => { if (value !== 0) { invokeHaptic() }}`
